import Header from '@/components/Header'
import LeftBar from '@/components/LeftBar'

export const metadata = {
  title: 'Tasks Planning | Board',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <main id='main-page' className="min-h-screen w-full text-slate-950 dark:text-slate-100  bg-gradient-to-r from-blue-400 to-blue-600">
        <Header />
        <div className='flex px-0 py-0 m-0 w-full gap-0 min-h-[calc(100vh-5rem)] overflow-y-scroll'>
          {/* Left bar */}
          <div className="z-50 flex flex-col backdrop-blur-xl bg-slate-50/20 dark:bg-slate-950/50 min-w-[260px] md:w-[320px] max-w-[260px] md:max-w-[320px]">
            <LeftBar />
          </div>
          {/* Right panel */}
          <div className="w-full z-0">
            {children}
          </div>

          {/* Allow more space for Mobile devices */}
          <div className="hidden sm:h-20" />
        </div>
        
    </main>
  )
}
